import{a as w,i as c,S as P}from"./assets/vendor-b0d10f48.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const S="36655990-0724db180fb71d9be8c2c1bf3",E="https://pixabay.com/api/?key=",$="&image_type=photo&orientation=horizontal&safesearch=true&per_page=15";async function h(o,t){try{return(await w.get(E+S+`&q=${o}`+$+`&page=${t}`)).data}catch{throw new Error("Failed to fetch photos")}}function g(o,t){const i=o.map(({webformatURL:n,largeImageURL:e,tags:r,likes:a,views:v,comments:L,downloads:b})=>`
      <div class="photo-card">
        <a href="${e}">
          <img src="${n}" alt="${r}" loading="lazy" max-width="400px" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b><br>${a}</p>
          <p class="info-item"><b>Views</b><br>${v}</p>
          <p class="info-item"><b>Comments</b><br>${L}</p>
          <p class="info-item"><b>Downloads</b><br>${b}</p>
        </div>
      </div>
    `).join("");t.insertAdjacentHTML("beforeend",i)}const f=document.querySelector(".search-form"),u=document.querySelector(".js-search-list"),l=document.querySelector(".js-loader"),p=document.querySelector(".js-load-more-loader"),s=document.querySelector(".js-load-more-btn");let m=1,d="";f.addEventListener("submit",async o=>{if(o.preventDefault(),d=f.elements.enterForSearch.value.trim(),!!d){s.classList.contains("active")&&s.classList.remove("active"),u.innerHTML="",l.classList.add("active"),m=1;try{const{data:t}=await h(d,m);if(!t.totalHits){l.classList.remove("active"),c.error({title:"Error",message:"No images found matching your search query. Please try again!",position:"topRight"}),f.reset();return}g(t.hits,u),l.classList.remove("active"),s.classList.add("active"),t.totalHits<15&&(s.classList.remove("active"),c.info({title:"Info",message:"We're sorry, but you've reached the end of the results.",position:"topRight"})),y.refresh()}catch(t){console.log(t),l.classList.remove("active"),c.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})}}});s.addEventListener("click",async()=>{p.classList.add("active"),s.classList.remove("active");try{const{data:o}=await h(d,++m);g(o.hits,u),p.classList.remove("active"),s.classList.add("active"),y.refresh(),window.scrollBy({top:u.firstChild.getBoundingClientRect().height*2,behavior:"smooth"}),m*15>=o.totalHits&&(s.classList.remove("active"),c.info({title:"Info",message:"We're sorry, but you've reached the end of the results.",position:"topRight"}))}catch(o){console.log(o),p.classList.remove("active"),c.error({title:"Error",message:"Failed to load more images. Please try again later.",position:"topRight"})}});const y=new P(".gallery a",{captionsData:"alt",captionDelay:250});
//# sourceMappingURL=commonHelpers.js.map
