import{a as L,i,S as v}from"./assets/vendor-b0d10f48.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const w="36655990-0724db180fb71d9be8c2c1bf3",P="https://pixabay.com/api/?key=",E="&image_type=photo&orientation=horizontal&safesearch=true&per_page=15";async function h(r,t){try{return(await L.get(P+w+`&q=${r}`+E+`&page=${t}`)).data}catch{throw new Error("Failed to fetch photos")}}function u(r,t){const a=r.map(({webformatURL:c,largeImageURL:e,tags:o,likes:l,views:m,comments:g,downloads:b})=>`
      <div class="photo-card">
        <a href="${e}">
          <img src="${c}" alt="${o}" loading="lazy" max-width="400px" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b><br>${l}</p>
          <p class="info-item"><b>Views</b><br>${m}</p>
          <p class="info-item"><b>Comments</b><br>${g}</p>
          <p class="info-item"><b>Downloads</b><br>${b}</p>
        </div>
      </div>
    `).join("");t.insertAdjacentHTML("beforeend",a)}const f=document.querySelector(".search-form"),p=document.querySelector(".gallery"),s=document.querySelector(".load-more"),n=document.querySelector(".loader");let y=1,d="";s.style.display="none";n.style.display="none";f.addEventListener("submit",async r=>{if(r.preventDefault(),d=f.elements.searchQuery.value.trim(),!d){i.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}p.innerHTML="",y=1,s.style.display="none",n.style.display="block";try{const t=await h(d,y);if(t.hits.length===0){i.warning({title:"Warning",message:"No images found for your search query.",position:"topRight"}),n.style.display="none";return}u(t.hits,p),t.hits.length<15?(s.style.display="none",i.info({title:"Info",message:"You have reached the end of the images.",position:"topRight"})):s.style.display="block"}catch(t){console.error("Error fetching photos:",t),i.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})}finally{n.style.display="none"}});s.addEventListener("click",async()=>{s.style.display="none",n.style.display="block";try{const r=await h(d,++y);u(r.hits,p),r.hits.length<15?(s.style.display="none",i.info({title:"Info",message:"You have reached the end of the images.",position:"topRight"})):s.style.display="block"}catch(r){console.error("Error fetching more photos:",r),i.error({title:"Error",message:"Failed to load more images. Please try again later.",position:"topRight"})}finally{n.style.display="none"}});new v(".gallery a",{captionsData:"alt",captionDelay:250});
//# sourceMappingURL=commonHelpers.js.map
